version: '2'
services:
  scaffold:
    build: .
    volumes:
     - .:/usr/src/app
    command: python manage.py runserver --host=0.0.0.0
    environment:
     - PIP_INDEX_URL=https://pypi.tuna.tsinghua.edu.cn/simple
     - FLASK_CONFIG=development
    links:
      - database
    depends_on:
      - database
    ports:
      - 5000:5000
  database:
    image: mysql:5.7
    volumes:
      - ./db:/var/lib/mysql/data
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
